# Site settings
title: Michael Kamin
description: the funny
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Kamin
user_description: lorum ipsum or something idk
user_title: Funny guy
email: buythedomainfirstyoumoron
twitter_username: MichaelKamin007
# instagram_username: michaelkamin007
# facebook_username: balls
# linkedin_username: balls
github_username:  TheMichaelKamin
medium_username: 5854966593
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
